version: "3"
services:
  server:
    image: nuxtcrud.azurecr.io/nuxt-crud-server:1.0
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    networks:
      - net
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
  client:
    image: nuxtcrud.azurecr.io/nuxt-crud-client:1.0
    ports:
      - "80:80"
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - API_URL=http://server:3000/
    networks:
      - net
    depends_on:
      - server
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
networks:
  net: