# This is a basic workflow to help you get started with Actions

name: Continuous Integration & Continuous Deployment

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains three jobs called "build-server" "build-client" "deployment"
  # build-server:
  #   name: Build server
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - name: Checkout server code
  #       uses: actions/checkout@v2

  #     - name: Setup node version
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '14.x'

  #     - name: Install dependencies
  #       working-directory: ./server
  #       run: npm install

  #     # Runs a set of commands using the runners shell
  #     - name: Run tests
  #       working-directory: ./server
  #       run: npm run test 

  #     - name: Login to Azure Container Registry
  #       uses: azure/docker-login@v1
  #       with:
  #         login-server: nuxtcrud.azurecr.io
  #         username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
  #         password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

  #     - run: |
  #         docker build ./server -t nuxtcrud.azurecr.io/nuxt-crud-server:v0.2
  #         docker push nuxtcrud.azurecr.io/nuxt-crud-server:v0.2

  # build-client: 
  #   name: Build client

  #   runs-on: ubuntu-latest

  #   steps: 
  #     - name: Checkout client code
  #       uses: actions/checkout@v2

  #     - name: Setup node version
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '14.x'

  #     - name: Install dependencies
  #       working-directory: ./client
  #       run: npm install

  #     - name: Nuxt build/start & Cypress run
  #       uses: cypress-io/github-action@v2
  #       with:
  #         browser: chrome
  #         headless: true
  #         working-directory: ./client
  #         build: npm run build
  #         start: npm run start
  #         # quote the url to be safe against YML parsing surprises
  #         wait-on: 'http://localhost:8000'
  #         # spec: cypress/integration/routeHome.spec.js

  #     - name: Login to Azure Container Registry
  #       uses: azure/docker-login@v1
  #       with:
  #         login-server: nuxtcrud.azurecr.io
  #         username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
  #         password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

  #     - run: |
  #         docker build ./client -t nuxtcrud.azurecr.io/nuxt-crud-client:v0.2
  #         docker push nuxtcrud.azurecr.io/nuxt-crud-client:v0.2

  deployment:
    name: Deploy to Azure 

    runs-on: ubuntu-latest

    # wait until Jobs are finished
    # needs: [build-server, build-client]

    steps:
      - name: Checkout containers
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: nuxtcrud.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name:
        uses: azure/login@v1
        with: Login to Azure 
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Deploy Azure webapps Container
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'nuxtcrud'
          #publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: |
            nuxtcrud.azurecr.io/nuxt-crud-server:1.0
            nuxtcrud.azurecr.io/nuxt-crud-client:1.0
          configuration-file: . docker-compose.azure.yml